### PR TITLE
Introduced new parameters

### PR DESCRIPTION
**Pull request by wsromek**
Introduced new parameters to allow fetching all the subsections of a section when using "auto" method
@mplachta

### CODE REVIEW

**Comment by arkadiuszmalina** [comment]
:+1:

**Comment by mplachta** [comment]
Cool, I'll bump version in a few minutes.

**Comment by ralfmaxxx** [comment]
:+1:

**Comment by filipgolonka** [comment]
:+1:

**Comment by mplachta** [comment]
Update docs

**Comment by mplachta** [comment]
And command

**Comment by mplachta** [comment]
@wsromek great, squash and I'll merge

**Pull request merged**
